import Link from 'next/link';
import { deleteContent, saveContent } from './actions';

type Item=Record<string,unknown>;
type Choice={id:string;name:string};

export default function ContentForm({type,item,locations,monuments,message,canDelete=false}:{type:string;item?:Item;locations:Choice[];monuments:Choice[];message?:string;canDelete?:boolean}){
  const id=String(item?.id??'');
  const v=(key:string)=>String(item?.[key]??'');
  const status=String(item?.status??'draft');
  return <>
    {message&&<p className="notice">{message}</p>}
    <form action={saveContent} className="contribution-form" encType="multipart/form-data">
      <input type="hidden" name="type" value={type}/>{id&&<input type="hidden" name="id" value={id}/>} 
      {(type==='locations'||type==='monuments')&&<label>Nombre<input name="name" required defaultValue={v('name')}/></label>}
      {type==='locations'&&<><div className="form-row"><label>País<input name="country" required defaultValue={v('country')||'España'}/></label><label>Región<input name="region" defaultValue={v('region')}/></label></div><label>Descripción<textarea name="description" rows={7} defaultValue={v('description')}/></label><div className="form-row"><label>Latitud<input name="latitude" type="number" min="-90" max="90" step="any" required defaultValue={v('latitude')}/></label><label>Longitud<input name="longitude" type="number" min="-180" max="180" step="any" required defaultValue={v('longitude')}/></label></div></>}
      {type==='monuments'&&<><label>Localidad<select name="location_id" required defaultValue={v('location_id')}><option value="">Seleccionar…</option>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Descripción<textarea name="description" rows={7} defaultValue={v('description')}/></label><div className="form-row"><label>Siglo<input name="century" defaultValue={v('century')}/></label><label>Estilo<input name="style" defaultValue={v('style')}/></label><label>Tipo arquitectónico<input name="architectural_type" defaultValue={v('architectural_type')}/></label></div><label>Referencia patrimonial<input name="heritage_reference" defaultValue={v('heritage_reference')}/></label><label>Web<input name="website_url" type="url" defaultValue={v('website_url')}/></label></>}
      {type==='posts'&&<><label>Título<input name="title" required defaultValue={v('title')}/></label><label>Entradilla<textarea name="excerpt" rows={3} defaultValue={v('excerpt')}/></label><label>Contenido<textarea name="body" rows={14} required defaultValue={v('body')}/></label><label>Fecha de publicación<input name="published_at" type="datetime-local" defaultValue={v('published_at').slice(0,16)}/></label></>}
      {type==='events'&&<><label>Título<input name="title" required defaultValue={v('title')}/></label><label>Descripción<textarea name="description" rows={7} defaultValue={v('description')}/></label><div className="form-row"><label>Inicio<input name="starts_at" type="datetime-local" required defaultValue={v('starts_at').slice(0,16)}/></label><label>Fin<input name="ends_at" type="datetime-local" defaultValue={v('ends_at').slice(0,16)}/></label></div><div className="form-row"><label>Localidad<select name="location_id" defaultValue={v('location_id')}><option value="">Sin localidad</option>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Aforo<input name="capacity" type="number" min="1" step="1" defaultValue={v('capacity')}/></label></div></>}
      {type==='media'&&<><div className="form-row"><label>Título<input name="title" defaultValue={v('title')}/></label><label>Tipo<select name="media_type" defaultValue={v('media_type')||'image'}><option value="image">Imagen</option><option value="video">Vídeo</option><option value="document">Documento</option></select></label></div><label>Descripción<textarea name="description" rows={5} defaultValue={v('description')}/></label><p className="muted">Asocia el medio a una localidad o a un monumento, pero no a ambos.</p><div className="form-row"><label>Localidad<select name="location_id" defaultValue={v('location_id')}><option value="">Sin localidad</option>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Monumento<select name="monument_id" defaultValue={v('monument_id')}><option value="">Sin monumento</option>{monuments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><label>Archivo nuevo<input name="file" type="file"/></label>{v('storage_path')&&<p className="muted">Archivo actual: {v('storage_path')}</p>}<label>URL externa<input name="external_url" type="url" defaultValue={v('external_url')}/></label><div className="form-row"><label>Miniatura (ruta)<input name="thumbnail_path" defaultValue={v('thumbnail_path')}/></label><label>Orden<input name="sort_order" type="number" step="1" defaultValue={v('sort_order')||'0'}/></label></div></>}
      <label>Estado<select name="status" defaultValue={status}><option value="draft">Borrador</option><option value="published">Publicado</option><option value="archived">Archivado</option></select></label>
      <div className="form-actions"><button type="submit">Guardar</button><Link className="button-link secondary" href={`/admin/contenidos/${type}`}>Volver</Link></div>
    </form>
    {id&&canDelete&&status==='archived'&&<form action={deleteContent} className="danger-zone"><input type="hidden" name="type" value={type}/><input type="hidden" name="id" value={id}/><p>El borrado físico está reservado a administradores y solo para contenido archivado. Puede fallar si existen elementos asociados.</p><label>Escribe <strong>ELIMINAR</strong> para confirmar<input name="confirmation" required pattern="ELIMINAR" autoComplete="off"/></label><button type="submit">Eliminar definitivamente</button></form>}
  </>;
}
