import { createClient } from '../../../lib/supabase/server';
import { addRouteStop, deleteRouteStop, saveRoute } from './actions';

export default async function AdminRoutesPage({searchParams}:{searchParams:Promise<{mensaje?:string}>}){
  const supabase=await createClient();
  const [{data:routes},{data:stops},{data:locations},{data:monuments}]=await Promise.all([
    supabase.from('heritage_routes').select('*').order('title'),
    supabase.from('heritage_route_stops').select('*').order('route_id').order('sort_order'),
    supabase.from('locations').select('id,name,country,region').eq('status','published').order('name'),
    supabase.from('monuments').select('id,name,location_id').eq('status','published').order('name'),
  ]);
  const {mensaje}=await searchParams;
  const locationNames=new Map((locations??[]).map(x=>[x.id,x.name]));
  const monumentNames=new Map((monuments??[]).map(x=>[x.id,x.name]));
  return <>
    <header className="page-heading"><div><div className="muted">Administración · Patrimonio</div><h1>Rutas románicas</h1><p>Crea itinerarios y ordena localidades o monumentos como paradas visitables.</p></div></header>
    {mensaje&&<p className="notice">{mensaje}</p>}
    <section className="form-section"><h2>Nueva ruta</h2><form action={saveRoute} className="contribution-form"><div className="form-row"><label>Título<input name="title" required/></label><label>Slug<input name="slug" placeholder="se genera automáticamente"/></label></div><div className="form-row"><label>País<input name="country"/></label><label>Región<input name="region"/></label></div><div className="form-row"><label>Distancia (km)<input type="number" min="0" step="0.1" name="distance_km"/></label><label>Duración<input name="duration_text" placeholder="Ej. 2 días"/></label></div><label>Resumen<textarea name="summary" rows={2}/></label><label>Descripción<textarea name="description" rows={5}/></label><label>Estado<select name="status" defaultValue="draft"><option value="draft">Borrador</option><option value="published">Publicado</option><option value="archived">Archivado</option></select></label><button type="submit">Crear ruta</button></form></section>
    <section className="catalog-section"><div className="section-heading"><div><div className="eyebrow">Rutas</div><h2>{(routes??[]).length} itinerarios</h2></div></div><div className="stack-list">{(routes??[]).map(route=>{const routeStops=(stops??[]).filter(s=>s.route_id===route.id);return <article className="detail-copy" key={route.id}><div className="contribution-state">{route.status}</div><h2>{route.title}</h2><p>{route.summary||'Sin resumen.'}</p><form action={saveRoute} className="contribution-form"><input type="hidden" name="id" value={route.id}/><div className="form-row"><label>Título<input name="title" defaultValue={route.title} required/></label><label>Slug<input name="slug" defaultValue={route.slug} required/></label></div><div className="form-row"><label>País<input name="country" defaultValue={route.country??''}/></label><label>Región<input name="region" defaultValue={route.region??''}/></label></div><div className="form-row"><label>Distancia (km)<input name="distance_km" type="number" min="0" step="0.1" defaultValue={route.distance_km??''}/></label><label>Duración<input name="duration_text" defaultValue={route.duration_text??''}/></label></div><label>Resumen<textarea name="summary" rows={2} defaultValue={route.summary??''}/></label><label>Descripción<textarea name="description" rows={4} defaultValue={route.description??''}/></label><label>Estado<select name="status" defaultValue={route.status}><option value="draft">Borrador</option><option value="published">Publicado</option><option value="archived">Archivado</option></select></label><button type="submit">Guardar cambios</button></form><h3>Paradas</h3>{routeStops.length?<div className="stack-list">{routeStops.map(stop=><div className="stack-card" key={stop.id}><div><strong>{stop.sort_order}. {stop.location_id?locationNames.get(stop.location_id):monumentNames.get(stop.monument_id)}</strong>{stop.note&&<p>{stop.note}</p>}</div><form action={deleteRouteStop}><input type="hidden" name="id" value={stop.id}/><button className="secondary" type="submit">Quitar</button></form></div>)}</div>:<div className="empty-state">Sin paradas.</div>}<form action={addRouteStop} className="contribution-form"><input type="hidden" name="route_id" value={route.id}/><div className="form-row"><label>Parada<select name="target" required><option value="">Seleccionar…</option><optgroup label="Localidades">{(locations??[]).map(x=><option key={x.id} value={`location:${x.id}`}>{x.name} · {x.region??x.country}</option>)}</optgroup><optgroup label="Monumentos">{(monuments??[]).map(x=><option key={x.id} value={`monument:${x.id}`}>{x.name}</option>)}</optgroup></select></label><label>Orden<input type="number" name="sort_order" defaultValue={routeStops.length+1}/></label></div><label>Nota<input name="note"/></label><button type="submit">Añadir parada</button></form></article>})}</div></section>
  </>;
}
